use gymapp00001;
INSERT INTO ingredientTypes (Ingredient_Type_Name) VALUES
('None Of The Above'),
('UnAssigned'),
('Breads'),
('Cake'),
('Cereals'),
('Cereal Bars'),
('Cheese'),
('Chocolate'),
('Desserts'),
('Eggs'),
('Fish'),
('Frozen Fruit'),
('Frozen Vegetables'),
('Fruit'),
('Fruit Juice'),
('Grains & Legumes'),
('Juice'),
('Lean Meat'),
('Liquids'),
('Meat'),
('Milk'),
('Noodles'),
('Nut Powder'),
('Nuts & Seeds'),
('Other Grains'),
('Pasta'), 
('Plant Milk'),
('Poultry'),
('Potatoes'),
('Protein Powder'),
('Rice'),
('Sauce'),
('Smoothie'),
('Spices And Herb Packs'),
('Syrup And Spreads'),
('Vegan Vitamin Powders'),
('Vegan Milk'),
('Vegetables'),
('Vitamins'),
('Whole Wheat'),
('Yoghurt')

;

