name: Commit Message Lint

on:
  pull_request:
    branches: [master]
  push:
    branches: ['**']

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install commitlint
        run: npm install --no-save @commitlint/config-conventional @commitlint/cli

      - name: Run commitlint for push
        if: github.event_name == 'push'
        shell: bash
        run: |
          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
            npx commitlint --last --verbose
          else
            npx commitlint --from "${{ github.event.before }}" --to "${{ github.sha }}" --verbose
          fi

      - name: Run commitlint for pull request
        if: github.event_name == 'pull_request'
        run: npx commitlint --from "${{ github.event.pull_request.base.sha }}" --to "${{ github.event.pull_request.head.sha }}" --verbose